version: '3.8'

services:
  php:
    image: php:8.1-fpm-alpine
    volumes:
      - ./src:/var/www/html
    ports:
      - 9990:80

  mysql:
    image: mysql:8.0
    environment:
      - DATABASE=three_tier_website
      - USERNAME=root
      - PASSWORD=password
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8880:8080

# Run docker-compose up
docker-compose up -d
